<?php

namespace iMVC\Routing;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 16:50:02.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers iMVC\Routing\Request::WithRequest
     * @todo   Implement testWithRequest().
     */
    public function testWithRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::setURI
     * @todo   Implement testSetURI().
     */
    public function testSetURI() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::getRequestURI
     * @todo   Implement testGetRequestURI().
     */
    public function testGetRequestURI() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::LoadControllerFile
     * @todo   Implement testLoadControllerFile().
     */
    public function testLoadControllerFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::IsGET
     * @todo   Implement testIsGET().
     */
    public function testIsGET() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::GetGET
     * @todo   Implement testGetGET().
     */
    public function testGetGET() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::IsPOST
     * @todo   Implement testIsPOST().
     */
    public function testIsPOST() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::GetPOST
     * @todo   Implement testGetPOST().
     */
    public function testGetPOST() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Routing\Request::SendInteralRequest
     * @todo   Implement testSendInteralRequest().
     */
    public function testSendInteralRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
