<?php

namespace iMVC\Tools;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 17:05:19.
 */
class DebugTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Debug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Debug;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers iMVC\Tools\Debug::_var
     * @todo   Implement test_var().
     */
    public function test_var() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Tools\Debug::stack_trace
     * @todo   Implement testStack_trace().
     */
    public function testStack_trace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\Tools\Debug::backtrace
     * @todo   Implement testBacktrace().
     */
    public function testBacktrace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
