<?php

namespace iMVC\Tools;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 17:05:20.
 */
class Ini_ParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Ini_Parser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Ini_Parser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers iMVC\Tools\Ini_Parser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
