#!/bin/bash
echo "Cloning from online repository..." 
rm php-activerecord -R
git clone git@github.com:dariushha/php-activerecord.git -v
echo "Cloning all branches ..."
cd php-activerecord
for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do
    git branch --track ${branch##*/} $branch
done
git pull --all
echo "Done!"
cd ../..

