<div>    
    <script>
        $('form#rename-folder-form').submit(function($e){
            $e.preventDefault();
            $.post($('form#rename-folder-form').attr('action')+'&ajax',
                    $('form#rename-folder-form').serialize(), 
                    function(data) {
                        $("#create-box").modal("hide");
                        if(data.length)
                            modalAlert(data, undefined, function(){
                                Reload("folder");
                            });
                        else
                            Reload("folder");
                    });
        });
    </script>
    <form action="/folder/rename?<?php echo $this->GetSecureGET(array($this->f, $this->p)); ?>" id='rename-folder-form' method="post">
        <input type='hidden' name='f' value='<?php echo $this->f ?>' />
        <input type='hidden' name='p' value='<?php echo $this->p ?>' />
        <div class="input-append span12" style='margin-left: 6px;'>
            <input class="span10" style='' id="appendedInputButton" type="text" maxlength="75" name="folder_name" placeholder="Enter folder's name" required="" value="<?php echo $this->fname ?>">
            <button class="btn btn-primary" type="submit">Rename</button>
        </div>
    </form>
</div>