<?php

namespace iMVC\Layout;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 16:50:04.
 */
class BaseLayoutTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BaseLayout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BaseLayout(new \iMVC\View\BaseView(new \iMVC\Routing\Request));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers iMVC\Layout\BaseLayout::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate() {
        $this->object->Initiate();
        $this->assertEquals($this->object->GetLayoutName(), "default");
        $this->assertFalse($this->object->IsLayoutSuppressed());
    }

    /**
     * @covers iMVC\Layout\BaseLayout::Render
     * @todo   Implement testRender().
     */
    public function testRender() {
        $this->object->view->index_title = "TESting";
        $this->object->Render();
    }

    /**
     * @covers iMVC\Layout\BaseLayout::SetLayout
     * @todo   Implement testSetLayout().
     */
    public function testSetLayout() {
        $this->object->SetLayout("foo");
        $this->assertequals("foo",$this->object->GetLayoutName());
        $this->object->SetDefaultLayout();
        $this->assertequals("default", $this->object->GetLayoutName());
    }

    /**
     * @covers iMVC\Layout\BaseLayout::SuppressLayout
     * @todo   Implement testSuppressLayout().
     */
    public function testSuppressLayout() {
        $this->object->SuppressLayout();
        $this->asserttrue($this->object->IsLayoutSuppressed());
        $this->object->SuppressLayout(false);
        $this->assertfalse($this->object->IsLayoutSuppressed());
    }

    /**
     * @covers iMVC\Layout\BaseLayout::IsLaSuppressed
     * @todo   Implement testIsLayoutSuppressed().
     */
    public function testIsLayoutSuppressed() {
        $this->testSuppressLayout();
    }

    /**
     * @covers iMVC\Layout\BaseLayout::GetLayoutName
     * @todo   Implement testGetLayoutName().
     */
    public function testGetLayoutName() {
        $this->testSetLayout();
    }

    /**
     * @covers iMVC\Layout\BaseLayout::GetLayoutPath
     * @todo   Implement testGetLayoutPath().
     */
    public function testGetLayoutPath() {
        $this->object->SetDefaultLayout();
        $this->assertequals(MODULE_PATH."Default/Views/Layout/default.phtml", $this->object->GetLayoutPath());
        $this->object->SetLayout("foo");
        $this->assertequals(MODULE_PATH."Default/Views/Layout/foo.phtml", $this->object->GetLayoutPath());
    }

}
