<?php

namespace iMVC\APP;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 16:50:02.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers iMVC\APP\Application::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\APP\Application::Run
     * @todo   Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\APP\Application::Startup
     * @todo   Implement testStartup().
     */
    public function testStartup() {
        $this->assertTrue(isset($GLOBALS[CONFIGS]['init']['uri']));
    }

    /**
     * @covers iMVC\APP\Application::Shutdown
     * @todo   Implement testShutdown().
     */
    public function testShutdown() {
        
    }

}
