<?php

namespace iMVC\View;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 16:50:03.
 */
class BaseViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BaseView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BaseView(new \iMVC\Routing\Request);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers iMVC\View\BaseView::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::SetView
     * @todo   Implement testSetView().
     */
    public function testSetView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::SuppressView
     * @todo   Implement testSuppressView().
     */
    public function testSuppressView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::IsViewSuppressed
     * @todo   Implement testIsViewSuppressed().
     */
    public function testIsViewSuppressed() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::Render
     * @todo   Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::GetViewName
     * @todo   Implement testGetViewName().
     */
    public function testGetViewName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::GetViewPath
     * @todo   Implement testGetViewPath().
     */
    public function testGetViewPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\View\BaseView::RenderPartial
     * @todo   Implement testRenderPartial().
     */
    public function testRenderPartial() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
